name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["type:bug", "status:needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Navigate to '...'
        2. Click on '...'
        3. Observe error '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (include error messages if applicable)
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low - Minor inconvenience
        - Medium - Impacts functionality but has workaround
        - High - Blocks functionality, no workaround
        - Critical - Security issue or data loss
      default: 1
    validations:
      required: true

  - type: dropdown
    id: dotnet-version
    attributes:
      label: .NET Version
      description: Which .NET version are you using?
      options:
        - .NET 10 (LTS)
        - .NET 9 (STS - ends Nov 2026)
        - .NET 8 (LTS - ends Nov 2026)
        - Other (specify below)
      default: 0
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide additional environment details
      placeholder: |
        - OS: Windows 11 / macOS 15 / Ubuntu 24.04
        - Browser (if Blazor): Chrome 130 / Edge / Firefox
        - Module/Area: Auth, Blazor, API, etc.
      render: markdown

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any relevant log output or stack traces
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
